services:
  api:
    image: nguyenhuutan080603044/code-challenge:latest
    container_name: code_challenge_api 
    ports:
      - '3063:3063'
    environment:
      NODE_ENV: production
      PORT: 3063
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/code_challenge"
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_challenge
      POSTGRES_PORT: 5432
    command: ["node", "dist/index.js"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: code_challenge_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=code_challenge
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped